# Generated by Django 5.0.1 on 2024-06-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
