# Generated by Django 4.2.17 on 2024-12-10 14:47

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SimpleVideoOrderable',
        ),
        migrations.DeleteModel(
            name='VideoPage',
        ),
    ]
